# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cbb87d1db0b9fdbaf97cdd2bb533ca286609ad9cd76d8ccfed6788f3aea05796862c1a9ee47d2387b6ea5f649d86ca7b1e0ffee782f4a34fb3be2cd711c5c8d

test:
  secret_key_base: f63a5a43e90b7ca7ad2edaf24193905c5bc96155bd847b05af998771b448f68e868b10a2f8b94246e4405f40307e962aacb1b49db95c8ae99e3a1fdc06bbd07b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
